### ISSUE TITLE
Spaces Support

### ISSUE THREAD

**Issue by ethangunderson** [cyberdelia/heroku-go#9]
I'm looking to add support for the spaces api. Is this in the works by anyone else?

**Comment by pnc** [comment]
@ethangunderson Most of the source is generated, possibly by [this tool](https://github.com/interagent/schematic). You might have a go at regenerating from the [newest available schema[(https://blog.heroku.com/archives/2014/1/8/json_schema_for_heroku_platform_api#how-to-use-the-schema) and see what happens?

**Comment by ethangunderson** [comment]
Looks like the code generator no longer works because of this bug: https://github.com/interagent/schematic/issues/29
